modLoader="javafml"
loaderVersion="[24,)"
issueTrackerURL="https://github.com/CreativeMD/EnhancedVisuals/issues"
logoFile="enhancedvisuals.png"
license="GNU General Public License v3.0"

[[mods]]
	modId="enhancedvisuals"
	version="1.3.0"
	displayName="EnhancedVisuals"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/enhancedvisuals"
	authors=["CreativeMD", "Sonicjumper"]
	description='''Experience realism and extra video effects for your in-game experience.'''
	
[[dependencies.enhancedvisuals]]
	modId="creativecore"
	mandatory=true
	ordering="NONE"
	side="BOTH"
	versionRange="[2.4.0,)"