modLoader="javafml"
loaderVersion="[46,)"
issueTrackerURL="https://github.com/CreativeMD/EnhancedVisuals/issues"
license="LGPL-3.0-only"

[[mods]]
    modId="enhancedvisuals"
    logoFile="enhancedvisuals.png"
    version="1.7.2"
    displayName="EnhancedVisuals"
    displayURL="https://modrinth.com/mod/enhancedvisuals"
    authors="CreativeMD, Sonicjumper"
    description='''Experience realism and extra video effects for your in-game experience.'''

[[dependencies.enhancedvisuals]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.enhancedvisuals]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.enhancedvisuals]]
   modId="creativecore"
   mandatory=true
   ordering="NONE"
   side="BOTH"
   versionRange="2.11.5"

